### ISSUE TITLE
How to add description?

### ISSUE THREAD

**Issue by donaldjarmstrong** [sogko/graphql-schema-language-cheat-sheet#3]
Are adding descriptions supported?  I have not seen any examples on how to add description to types and fields.  Maybe...?

`type User {` 
 `id: ID! # field description`
 `name: String # A cool name for this user`
`}`

**Comment by gajus** [comment]
Adding description is going to be implementation specific. If you are using `graphql-js`, then support for adding description via comments has been added in v0.7.

See https://medium.com/apollo-stack/all-you-need-to-know-about-graphql-js-0-7-921e75dd7fd1#.t9csdknur

**Comment by sogko** [comment]
Hi guys,

I've added examples of comments usage, though like @gajus said, it is specific to the tool implementation. It would be useful to document your schema.

Thanks!
