### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by Everhusk** [sogko/graphql-schema-language-cheat-sheet#4]
Hey, great cheat sheet! Just one typo in the Enum section (STATE should be USER_STATE or vice versa) i.e.

enum USER_STATE {
   NOT_FOUND
   ACTIVE
   INACTIVE
   SUSPENDED
}
type Root {
   stateForUser(userID: ID!): USER_STATE!
   users(state: USER_STATE, limit: Int = 10): [User]
}

**Comment by sogko** [comment]
Hey @Everhusk 

Thanks for spotting that! Added the changes in 👍

Cheers!
